title: "dunnousername"
description: "This is the site of Henry L. In this site are my projects in the fields of data science, machine learning, and computer programming."
theme: jekyll-theme-cayman
plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  - index.md
  - projects.md
  - first-order-wrapper.md
  - spidergan.md
  - m3u8a2/m3u8a2.md
  - random/r00000.md
